!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  convex_hull_apha: 0.005
  distance_plane_threshold: 0.003
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      convex_hull_apha: 0.005
      distance_plane_threshold: 0.003
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x_max: 0.12
      x_min: -0.16
      y_max: 0.1
      y_min: -0.1
      z_max: 0.5
      z_min: 0.3
    state: []
  x_max: 0.12
  x_min: -0.16
  y_max: 0.1
  y_min: -0.1
  z_max: 0.5
  z_min: 0.3
state: []
